server:
  port: 8080

spring:
  application:
    name: ai-askquestion
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ai_askquestion?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: ai_askquestion
    password: ai_askquestion
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.ai.askquestion.domain
  configuration:
    map-underscore-to-camel-case: true

# AI Configuration
ai:
  # OpenAI API Configuration
  openai:
    #付费的
    api-key: api-key
    model-name: DeepSeek-R1-0528-Qwen3-8B
    temperature: 0.6
    max-tokens: 1000
    timeout: 60
    baseUrl: https://open.bigmodel.cn/api/paas/v4/

logging:
  level:
    root: INFO
    com.ai.askquestion: DEBUG
