CREATE DATABASE IF NOT EXISTS ai_askquestion DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

USE ai_askquestion;

CREATE TABLE IF NOT EXISTS question_record (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    question TEXT NOT NULL,
    answer MEDIUMTEXT NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
